name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Install dependencies, check code quality and build
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Detect affected packages
        run: |
          AFFECTED_COUNT=$(pnpm turbo run lint --dry=json --filter=...[origin/${{ github.base_ref }}] | jq '.tasks | length')
          echo "count=$AFFECTED_COUNT" >> $GITHUB_OUTPUT

          echo "Affected packages:"
          echo "$DRY_RUN" | jq -r '.tasks[].package'

      - name: Check formatting
        run: pnpm format:check

      - name: Lint, check types and build
        if: steps.affected.outputs.count != '0'
        run: pnpm turbo run lint --filter="...[origin/${{ github.base_ref }}]"
