name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

env:
  TURBO_SCM_BASE: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}

jobs:
  build:
    name: Install dependencies, check code quality and build
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Detect affected packages
        id: affected
        run: |
          DRY_RUN=$(pnpm turbo run check-types --dry=json --affected)
          AFFECTED_COUNT=$DRY_RUN | jq '.tasks | length'
          AFFECTED_PACKAGES=$DRY_RUN | jq '.tasks[].package'

          echo "$DRY_RUN"

          echo "count=$AFFECTED_COUNT" >> $GITHUB_OUTPUT

          echo "Affected packages:"
          echo "$AFFECTED_PACKAGES"

      - name: Check formatting
        run: pnpm format:check

      - name: Lint, check types and build
        if: steps.affected.outputs.count != '0'
        run: pnpm turbo run lint check-types build --affected
