name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

env:
  TURBO_SCM_BASE: ${{ github.event_name == 'pull_request' && github.event.pull_request.base.sha || github.event.before }}

jobs:
  build:
    name: Install dependencies, check code quality and build
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          filter: "blob:none"
          fetch-depth: 0

      - name: Fetch origin/main
        run: git fetch origin main:refs/remotes/origin/main

      - name: Fetch origin/foo
        run: git fetch origin foo:refs/remotes/origin/foo

      - name: Fetch PR head (if available)
        if: github.event_name == 'pull_request'
        run: git fetch origin ${{ github.head_ref }}:refs/remotes/origin/${{ github.head_ref }}

      - name: Test git diff
        run: git diff origin/main...HEAD

      - name: Debug Git refs
        run: |
          git branch -a
          git log -1
          git rev-parse origin/main || echo "origin/main missing"

      - uses: pnpm/action-setup@v3
        with:
          version: 8

      - name: Setup Node.js environment
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Detect affected packages
        id: affected
        run: |
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BASE_REF="origin/main"
            HEAD_REF="origin/${{ github.head_ref }}"
          else
            BASE_REF="${{ github.event.before }}"
            HEAD_REF="HEAD"
          fi

          echo "Comparing $BASE_REF → $HEAD_REF"

          AFFECTED_PACKAGES=$(TURBO_SCM_BASE=$BASE_REF TURBO_SCM_HEAD=$HEAD_REF pnpm turbo ls --output=json)
          echo "$AFFECTED_PACKAGES" | tee affected.json

          COUNT=$(echo "$AFFECTED_PACKAGES" | jq '.packages.items | length')
          echo "count=$COUNT" >> $GITHUB_OUTPUT

      - name: Packages affected using exact origin/main and origin/foo
        run: |
          AFFECTED_PACKAGES=$(TURBO_SCM_BASE=origin/main TURBO_SCM_HEAD=origin/foo pnpm turbo ls --affected --output=json)

          echo "Packages affected:"
          echo "$AFFECTED_PACKAGES" | jq '.packages.items'

      - name: Check formatting
        run: pnpm format:check

      - name: Lint, check types and build
        if: steps.affected.outputs.count != '0'
        run: pnpm turbo check-types --affected
